/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Day35Problems.JDBCTransaction;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
